### PR TITLE
Modify schedule function

### PR DESCRIPTION
**Pull request by JunsikChoi**
for more proper sorting

### CODE REVIEW

**Review by marin1602 — CHANGES_REQUESTED** [review]
👍

**Review by Chris-Graffagnino — CHANGES_REQUESTED** [review]
I really like this! Would you mind adding a line in the body of the function; something like:
`echo "Which block-dates are this node scheduled for this epoch?"`

**Comment by marin1602** [comment]
Hi Chris,

I'm not sure what to do with this line…

 

The node keeps forking, I had to restart a few times. Will this stabilise?

 

Thnx,

Marin

**Review by Chris-Graffagnino — APPROVED** [review]
Merging. I'll add the extra line ;)

**Pull request merged**
